### ISSUE TITLE
Talk about API to Project E

### ISSUE THREAD

**Issue by MajorBreakfast** [PokemonGoers/PokeMap-1#10]
Hey Map Team 1,

I'm from Project E AKA the UI team AKA your customer. Since you don't have an issue open where I could post what I'm going to say, I am so shameless and create one! Sorry for that!

I just wanted to announce that our team had a very productive team meeting yesterday in which we created an app storyboard with all screens of the app. Now, it is somewhat clear for us what we need. ~~I'm going to write down all the API features until this evening and then publish it as a first draft of the API. Then it will be feedback time :) I'll post a link in this issue here once it's ready.~~

SPOILER: Since all Pokemon data will flow through this API, it will also include functionality that is not directly map related. However, for you that will mean just a few additional JSON API calls.

**Edit** The current proposal is to have two client-side libraries: PokeData JS API and PokeMap JS API.

The PokeMap JS API issue https://github.com/PokemonGoers/Catch-em-all/issues/24

**Comment by sacdallago** [comment]
Same as https://github.com/PokemonGoers/PokeMap-2/issues/16#issuecomment-243988583

**Comment by gqinami** [comment]
Hey @MajorBreakfast, 

As per the issue from PokeMap2 group: [https://github.com/PokemonGoers/PokeMap-2/issues/16], we are a bit confused on the "API" that you want from us. From the issue of PokeMap2 it looked like you were going to discuss with Project A first. Please let us know how are we going to tackle this.

By the way, we are currently working on an self contained Angular module. What we can offer is a simple div (not now, in a few days :)), as specified by Guy in this issue: https://github.com/PokemonGoers/Catch-em-all/issues/9#issuecomment-243352183. To create also an idea of how our app will look like, you can have a look at our live demo here: https://pokemongoers.github.io/PokeMap-1/

Thanks,
PokeMap1

**Comment by MajorBreakfast** [comment]
The PokeMap JS API issue https://github.com/PokemonGoers/Catch-em-all/issues/24

@gqinami There is no need for you to develop a UI except the map itself since that is our team's main task after all :) We're still awaiting comments by the tutors. Anyway, let's keep the discussion in https://github.com/PokemonGoers/Catch-em-all/issues/24 and see how everything develops.

**Comment by sacdallago** [comment]
@gqinami yes @MajorBreakfast is right. You can develop a UI toolbar to test your functions a.s.o., but keep it separated from the map (aka: the slider that you just implemented calls functions on your tool, rather than making changes directly on the map). This way the web team can call the functions but implement a different tool-bar according to what they want (or simply copy yours and apply a few style changes).

**Comment by gqinami** [comment]
Since all the discussion for the interface is at https://github.com/PokemonGoers/Catch-em-all/issues/24, can we close this issue?

**Comment by sacdallago** [comment]
Looks like it
