### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by sacdallago** [PokemonGoers/PokeMap-1#11]
A thing that just popped to my mind: it would be extremely nice if you gave the users who use your package also the option to specify a different map provider.

Specifically [here](https://github.com/PokemonGoers/PokeMap-1/blob/develop/client/scripts/map/controllers/uiLeaflet.js#L30) you would need to change the line to accept a tile layer defined during initialization of your module.

I'm thinking about making my own style for the maps, either something like https://www.mapbox.com/maps/light-dark/ or.... OR... https://www.mapbox.com/blog/the-playful-design-of-pokemon-go-maps/

**Comment by gqinami** [comment]
Hi @sacdallago .

We added the tileLayer  parameter to our constructor, so the users of our package can specify a different map Provider. 

Is this what you requested?

P.S. we did this a long time ago :), but forgot to answer here in this issue.

**Comment by sacdallago** [comment]
yup, nice! I also am slow in answering these days, crappy internet when there's any
