### ISSUE TITLE
Integrate PokeMob detection from HashPokemonGo project

### ISSUE THREAD

**Issue by phdowling** [PokemonGoers/PokeMap-1#12]
Hey guys,

We wrote a PokeMob detection module. We listen for tweets with location tags, and if we detect a spike in locality, we trigger an event via a websocket. How difficult would this be for you guys to integrate?

The API is basically just the following: You open a websocket conenction to `/mobs/geo/all` (or `/mobs/geo/:lat/:lon/:radius` for location-based queries, though those will be even more rare), and every now and then, though very rarely, you will receive a JSON object with detected mobs. The goal would then be to display this live in the users map.

What are your thoughts?

**Comment by sacdallago** [comment]
Hi @phdowling ,
Just a note on the URL now that I see it: in order to stick to standards this should be a query URL, rather than a / separated URL:
- `/mobs/geo` --> `/mobs/geo/all`
- `/mobs/geo?lat=:lat&lon=:lon&r=:radius` --> `/mobs/geo/:lat/:lon/:radius`
- `/mobs/geo?lat=:lat&lon=:lon` --> same as above, but standard radius (for example 20km)

You need to check that if lon or lat are defined, also lat and lon are defined (respectively) :)

**Comment by phdowling** [comment]
Hey, updating this a bit: the API has now changed, instead of opening a socket to `/mobs/geo/:lat/:lon/:radius`, you directly access `/mobs` via a socket and then send your setting in a message once you are connected.

This code illustrates how you connect to the server:

``` javascript
var socket = io('http://localhost:3000/mobs');
socket.on("connect", function () {
    console.log("Connected to server, sending geo settings..");
    socket.emit("settings", {mode: "geo", lat: 1, lon:1, radius: 5000000});
});
// or:
/*socket.on('connect', function () {
    console.log("Connected to server, sending settings for listening to all clusters..");
    socket.emit("settings", {mode: "all"});
});*/
```

The returned JSON basically looks the same though. @PokemonGoers/pokemap-1   Is anyone from your team working on this? If you don't have the time, then maybe we could do a PR adding this functionality, however we would need some pointers as to where to start with integrating this.

**Comment by gqinami** [comment]
Hey @phdowling,

We are currently working on some other tasks but we will have a meeting today afternoon and will discuss this issue and will let you know if we need any other info / help :)

**Comment by gqinami** [comment]
Hi @phdowling,

Would it be ok for you or some other member of your Group for a 10-15 mins Meeting tomorrow before the presentations start to discuss regarding the Integration of PokeMob detection module in the map? I think it would be much easier than writing here :)

**Comment by gqinami** [comment]
This has been implemented long time ago :). Can we close this issue now?

**Comment by sacdallago** [comment]
Why do you even ask :D
