### ISSUE TITLE
PokeMap integration

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/PokeMap-1#15]
Hello PokeMap team,
I was able to look at your latest PR and give you some feedback now. First of all, this looks all really good to me and we can finally work with this! So thanks a lot for the effort.
I actually got the map running but I had to change a couple of things, so if you guys could fix these few things we're good to go.
### Prio 1

(Required to initialize the app)
- [x] Please specify the correct entry point in your `package.json`

``` (javascript)
// package.json
{
  //..
  "main": "module/main.js"
  /..
}
```
- [x] Your map is initialized on the html element with `id="mapid"` (`L.map('mapid')`). Please change that such that we can pass you a reference to the html element.

``` (javascript)
// module/main.js
function PokeMap(htmlElement, options) {
    // ...
   mymap = L.map(htmlElement)
   // ...
}
```
- [x] For the `PokeMap` constructor please adhere to the interface from https://github.com/PokemonGoers/Catch-em-all/issues/24. In particular:
  - The constructor only gets two parameters: `htmlElement` (HTML element reference) and `options` (Object).
  - The `options.coordinates` and `options.zoomLevel` options have been dropped. We will call the `goTo` method soon after the initialization. Until then please initialize the map to any location.
  - Please make use of the `options.apiEndpoint` parameter.
- [x]  Please change the method name `goto` to `goTo`.
- [x] The `goTo` method only receives one Object as parameter with keys `coordinates` and `zoomLevel`.
- [x] Please rename `lat` to `latitude` and `lng` to `longitude` in the `goTo` function.
- [x] In `module/main.js` you're making use of a global variable definition `window.L` (the Leaflet library). In the final app `window.L` won't be defined so please use some require mechanism (e.g. `var L = require('leaflet)`) to load the library.
- [x] The `apiEndpoint` value will look like `http://localhost:8080`. So if you want to make an API call the following would be wrong
  `dataService.getApiEndpointURL() + 'api/pokemon/'`
  and should be changed to
  `dataService.getApiEndpointURL() + '/api/pokemon/'`
- [x] In your `goTo` functions you have two small bugs. 
  1. The `coordinates` variable is not defined (only `coordinate`)
  2. The properties of the `coordinates` variable are called `longitude`/`latitude` not `latitud`/`longitud`. You would also need to change that in your constructor.
- [x] Merge back to develop
### Prio 2

(Required for interacting with the map. But at least we can see something already)
- [ ] `updateTimeRange` has been dropped in favor of the more general `filter`. This also adds an option to filter by pokemon id.
- [ ] Please rename the event `moveend` to `move`. The passed parameter of this event should be

``` (javascript)
fireEvent('move', {
    coordinates: {latitude: 47, longitude: 11},
    zoomLevel: 17
});
```
- [x] The `click` event is still missing. As parameter please pass the sighting, mob, or prediction that the user has clicked on (just pass the JSON response you get from the PokeData api).
- [x] Please add the `tileLayer` parameter to your constructor. For more information check the latest update from today in https://github.com/PokemonGoers/Catch-em-all/issues/24.

I will update this list continuously. If you have any questions please let me know.

**Comment by poulzinho** [comment]
@ukrainian256  @gqinami WIP in branch https://github.com/PokemonGoers/PokeMap-1/tree/feature/refactor-for-integration

**Comment by johartl** [comment]
Good progress!
I added three more points to the Prio1 list and one to the Prio2 list.

**Comment by johartl** [comment]
I will close this now and address the remaining problems (and further ones) in separate issues.
