### ISSUE TITLE
Running demo

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/PokeMap-1#18]
Hi guys,
I can't get your map to run. I tried importing it into our app and initialize it which won't work (no errors but nothing is displayed either).
Checking out your develop branch directly and opening the `index.html` also only gives me a blank page and throws two errors:

`Uncaught ReferenceError: require is not defined`
`Uncaught ReferenceError: PokeMap is not defined`

The live demo from your github pages works but is 20 days old.

I would really a need a working version of your map as soon as possible!

**Comment by gqinami** [comment]
@johartl normally it should work. We have tested it several times. However, we will have another look and let you know by the end of the day

**Comment by johartl** [comment]
Okay thank you. Can you also push the running version to your github pages afterwards please.

**Comment by oleks-fedotov** [comment]
@johartl Made a small fix, please try. But you have to run 'npm install' before using the app, because of leaflet dependency. Should you have questions or issues, please let us know. Have Fun 😃

**Comment by johartl** [comment]
The only change you've made was to comment out the `var L = require('leaflet')` call.
You're right, the `index.html` now works but Leaflet is not defined if I only include the `module/main.js` (which is the setup if we include it in the map in our app). This was the reason why we added the `require` in the first place.
But anyways, I feel like it's easier to just do the things that need to be done rather than telling you what to do step by step. So i created a pull request #19 that should resolve this issue.

**Comment by sacdallago** [comment]
How is this standing?

**Comment by gqinami** [comment]
Can we close this issue now? This is implemented long time ago
