### ISSUE TITLE
Trigger click and move events

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/PokeMap-1#20]
### `move` event

It seems like you're already triggering the `move` event, however, it is called `moveend` in your case. So first of all, please rename the event. 
The data attached to the move event currently looks like this

``` (json)
{
  "latlng": {
    "lat": 48.1832065,
    "lng": 11.6103129
  },
  zoom: 17
}
```

Please change it to look like this

``` (json)
{
  "coordinates": {
    "latitude": 48.1832065,
    "longitude": 11.6103129
  },
  zoomLevel: 17
}
```
### `click` event

The `click` event is not triggered at all right now.

**Comment by oleks-fedotov** [comment]
I think this issue can be closed, please review the last state of the develop branch
