### ISSUE TITLE
Pokemon sprites (icons)

### ISSUE THREAD

**Issue by gqinami** [PokemonGoers/PokeMap-1#24]
Hi @gyachdav,

We had a discussion about the pokemon icons and the right to use them. We downloaded them from this website: 
http://pokemondb.net
and in one of their FAQs, it is stated: 
**Can I use some content from your site?**

In general, no. All written content, site design and data display/layouts have had a huge amount of research and effort put into them to make as easy to read as possible. Do not steal our content!

However, official Pokémon artwork and sprites are not our creations and are used under a Fair Use Policy, so you are free to use them however you like. Each of the Pokémon sprites pages has an easy way to add images to your site or forum post.

Is it ok?

**Comment by sacdallago** [comment]
Mh, I don't get it. Where did you get the images from? That's the source that counts, nothing else.

If you can find the same images on a source that is CC0, then they are the ones in violations of copyrights, should there be any violations

**Comment by gqinami** [comment]
We downloaded the Images from the sites that I mentioned: http://pokemondb.net and they say that we are free to use them however we like.

**Comment by gqinami** [comment]
This is clear now. Closing this issue
