### ISSUE TITLE
Make use of websocketEndpoint parameter

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/PokeMap-1#25]
Hi everyone,
I just updated the PokeMap interface and added a constructor parameter `websocketEndpoint` that you should use to connect to the websockets for mobs and sentiments.

Here are the relevant information from https://github.com/PokemonGoers/Catch-em-all/issues/24
- `PokeMap(htmlElement, { filter, tileLayer, apiEndpoint, websocketEndpoint })` constructor that initializes the app at the given `htmlElement`.
  -  ...
  - `websocketEndpoint` The URI where the PokeData websocket runs on e.g. `http://pokedata.c4e3f8c7.svc.dockerapp.io:3322`. You can connect to the sockets for mobs and sentiments at `websocketEndpoint + '/mobs'` and `websocketEndpoint + '/sentiment'`, respectively.

**Comment by sacdallago** [comment]
As in https://github.com/PokemonGoers/PokeMap-2/issues/40#issuecomment-249413961

> published, should be pokedata.c4e3f8c7.svc.dockerapp.io:65024 though

**Comment by gqinami** [comment]
This is implemented as per the interface specifications. Can we close this issue now?
