### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/PokeMap-1#26]
Hi guys,
what's the latest news about releasing your code as npm package? I think you mentioned that you would be able to get this done by Sunday (today)?

**Comment by oleks-fedotov** [comment]
hi @johartl , we experienced some problems while publishing the package, but overall it's ready, would it be ok for you just to copy it manually for now, and we will fix that a bit later. Our team is currently trying to fix that

**Comment by poulzinho** [comment]
https://www.npmjs.com/package/pokemap-1

**Comment by johartl** [comment]
Thanks for publishing the npm package.
However it fails to install (`npm install pokemap-1`). I tried to fix this in this PR https://github.com/PokemonGoers/PokeMap-1/pull/27

**Comment by oleks-fedotov** [comment]
@johartl  merged, thanks

**Comment by johartl** [comment]
Can you republish the npm package from the latest sources then?

**Comment by oleks-fedotov** [comment]
@johartl republished

**Comment by sacdallago** [comment]
You can automate the publishing using travis-ci to check on version bumps on package.json, or (better) by releasing on master.

Btw: this issue = close?
