### ISSUE TITLE
One big fat Pikachu

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/PokeMap-1#32]
Hello,
with your latest npm release you broke our app. Please take a look yourself:
http://catch-em-all-0a600d65.c65978f4.svc.dockerapp.io:4898

The reason for that seem to be these lines:

``` (javascript)
// main.js
var loader = '<img id="pickachu-data-loading" src="' + image + '" />';
document.write(loader);
```

With that you're basically overwriting our app content. I understand that you're using the Pikachu image as loading screen. Please note that we already have a loading screen for our app so there is really no need to have another one for the map.

**Comment by oleks-fedotov** [comment]
@johartl fat pickachu is removed

**Comment by sacdallago** [comment]
:D I'm dying

**Comment by johartl** [comment]
Solved. Thanks!
