### ISSUE TITLE
navigate(): Naming of latitude and longitude parameters

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/PokeMap-1#34]
In your implementation of the navigate() function:

```
// main.js
function navigate(start, destination){
    if(route && route.removeFrom) {
        route.removeFrom(mymap);
    }
    route = L.Routing.control({
        waypoints: [
            L.latLng(start.lat, start.lng),
            L.latLng(destination.lat, destination.lng)
        ],
        collapsible: true,
        geocoder: L.Control.Geocoder.nominatim(),
        createMarker: function() { return null; } //removes the marker (we will use only pokemon icons as markers
    });
    route.addTo(mymap);
}
```

Your parameters are named `start.lat` and `start.lng`. However, they should really be named `start.latitude` and `start.longitude`. The same applies to `destination`. Please also see https://github.com/PokemonGoers/Catch-em-all/issues/24 for the original defintion.

**Comment by gqinami** [comment]
We implemented this. Please check the latest npm version. Can we close this issue now?

**Comment by sacdallago** [comment]
if @johartl tested it out, or @WoH

**Comment by johartl** [comment]
Yup it's fine!
