### ISSUE TITLE
Map update in infinite loop

### ISSUE THREAD

**Issue by johartl** [PokemonGoers/PokeMap-1#35]
In your latest npm release (0.1.4) I found a bug that causes infinitely many API requests. To reproduce
1. Open the map on http://catch-em-all-0a600d65.c65978f4.svc.dockerapp.io:4898 
2. Open the developer console on the console or network tab
3. Move the map, zoom in and out

Eventually you will see many `map:onMove` debug statements in the developer console or, if you switch to the network tab, hundreds of API requests to `/api/sightings/coordinates/from/..`.

My guess is that something in your `moveCallback` function is triggering the map to be moved again which, in return, triggers your `moveCallback`, and so on.

**Comment by oleks-fedotov** [comment]
That's pretty strange behavior. Will have a look at it. Also from the console(move event is currently logged there) you can see, that position is the same. In our `moveCallback` function we are only getting information about current location and zoomLevel and propagating the event. Locally this bug is not reproducible. 

What i can suggest as a solution: make a callback being a debounced function, to reduce the number of requests and also check the previous position and zoom-level with a current one - to prevent same requests.

**Comment by johartl** [comment]
> What i can suggest as a solution: make a callback being a debounced function, to reduce the number of requests and also check the previous position and zoom-level with a current one - to prevent same requests.

I feel like this is just fighting the symptons. I'd prefer if we could resolve the cause for this error. I'm gonna double check if the error is not on our side but it has always worked fine until we updated your pokemap.

**Comment by oleks-fedotov** [comment]
@johartl yes, on the one hand you're absolutely right. On the other - this will improve the performance a bit anyway. Because it doesn't cause only one move event, when you're zooming or moving for example. So i'll make that improvement meanwhile you're checking your side.

**Comment by johartl** [comment]
It's fine if you debounce the API calls on your side but please still trigger the `move` event undebounced. We would like to have consistent behavior here between the two map implementations.

**Comment by oleks-fedotov** [comment]
- Debounce API call implemented
- check for same coordinates and zoom level implemented
- dragend leaflet map event subscription removed(look like it's useless, so having movend completely enough)

Package was republished

**Comment by johartl** [comment]
@ukrainian256 I checked again and the error must be at your side. I tried previous versions of your npm release and found the following.
- `pokemap-1@0.1.1` works fine
- `pokemap-1@0.1.2` can't be tested because of the Pikachu bug
- `pokemap-1@0.1.3` does not work

**Comment by poulzinho** [comment]
We have changed leaflet version. Let us know if the problem persists with pokemap-1@0.1.6 (the current one)

**Comment by johartl** [comment]
`pokemap-1@0.1.6` works again. Thanks!
