### ISSUE TITLE
npm version broken

### ISSUE THREAD

**Issue by WoH** [PokemonGoers/PokeMap-1#40]
Hey guys, I started running into issues with your latest version on npm.
Can you please look into that?
Also, please note that it's hard to keep track of issues if you push changes without bumping the version number.
This is happening using npm version 0.1.6.

![screenshot from 2016-10-15 14-41-04](https://cloud.githubusercontent.com/assets/2697771/19410202/1d5b7a92-92e6-11e6-903b-cdd4590b7206.png)

**Comment by gqinami** [comment]
@WoH please test the new npm version and let us know if you have any issues

**Comment by WoH** [comment]
I was just about to comment, just a minor thing:

https://github.com/PokemonGoers/PokeMap-1/blob/develop/module/DataService.js#L17

> var url = apiEndpoint + '/api/pokemon/sighting/ts/' + sightingsSinceDate.toUTCString() + '/range/' + range.toString() + 'm';

won't work because you can't call toUTCString() on a number.

**Comment by gqinami** [comment]
We are calling it in a date, not in a number

**Comment by WoH** [comment]
I realized npm didn't update properly after I bumped the version, one sec.

**Comment by WoH** [comment]
![screenshot from 2016-10-23 15-58-06](https://cloud.githubusercontent.com/assets/2697771/19626825/8ef62c3e-9939-11e6-8147-249f1cda7df9.png)

Still working on this right now. It should never end up trying to polyfill if it's a date, that's weird. Ill investigate.

Edit: 
![screenshot from 2016-10-23 16-06-57](https://cloud.githubusercontent.com/assets/2697771/19626860/c7c2f686-993a-11e6-98dc-b3876e4b6b8d.png)

Still old version, I'm a monkey :see_no_evil: 

Edit 2: Cleaned up npm cache, will be back in a sec.

Also I'll tag @johartl.

**Comment by sacdallago** [comment]
@WoH you just mentioned one my favorite things ever ever. Those little fuckers are some of the cutest animals around (and I see them daily here!)
![dsc_2265](https://cloud.githubusercontent.com/assets/6240943/19626946/3d121226-996f-11e6-9ffe-928db0db7505.JPG)

**Comment by poulzinho** [comment]
I was expecting this
![real-code-monkey](https://cloud.githubusercontent.com/assets/3537214/19626993/cfe3c02c-993d-11e6-8cbd-bbccb84c6a8a.jpg)

**Comment by gqinami** [comment]
Are you sure that is the latest version. In the latest version it should be sightingsSinceDate.toUTCString(), not sightingsSince.toUTCString().

**Comment by WoH** [comment]
See me second edit. I had another version 0.1.8 cached I believe.

**Comment by WoH** [comment]
Ok, we good for now, seeing Mobs & Pokémon. However, the Pokémon seem to disappear when I move around.
