### ISSUE TITLE
_.debounce is not a function

### ISSUE THREAD

**Issue by MajorBreakfast** [PokemonGoers/PokeMap-1#44]
See https://github.com/PokemonGoers/Catch-em-all/issues/153

**Comment by oleks-fedotov** [comment]
Investigated a problem. Seems, it's a browserify-lodash problem. So lodash is not imported in our package correctly. What is also strange, that locally it works fine.

**Comment by MajorBreakfast** [comment]
Thx for investigating. Swift fix would be appreciated ;)

**Comment by oleks-fedotov** [comment]
Please check the new version of the package(0.1.9) - the problem should be fixed.

**Comment by MajorBreakfast** [comment]
Thx
