### ISSUE TITLE
Pokemon icons

### ISSUE THREAD

**Issue by gqinami** [PokemonGoers/PokeMap-1#7]
@sacdallago we at PokeMap-1 are wondering whether we should download all the pokemon icons and store them in a separate folder within the project (i.e. images), or, Project A that is collecting data about pokemons will do that and store the ikons for all pokemons as an attribute in the database?

**Comment by gyachdav** [comment]
Please coordinate with project A. Since the icons are most likely to be reusable across the project it is better they go in a central repo. I recommend you open an issue on A and ask for a model to be created and an endpoint that will allow you to upload the icons.
